// ============================================================================
//  DBR Check — sample report data
//  A realistic Design Basis Report: "Meridian Heights", G+12 RC residential
//  tower, Seismic Zone IV (Mumbai), M30 / Fe500, raft foundation.
//  25 checks across 9 categories, each with expected/found + IS-clause citation.
// ============================================================================

const DBR_META = {
  project: 'Meridian Heights — Tower B',
  doc: 'DBR-MH-TB-R2.pdf',
  pages: 34,
  uploaded: 'Today, 14:32',
  engineer: 'Structural Basis of Design',
};

// Extracted building profile — every field editable inline in the report.
const EXTRACTED = [
  { id: 'material',   label: 'Primary material',  value: 'RCC',            unit: '',     conf: 0.98 },
  { id: 'system',     label: 'Lateral system',    value: 'SMRF',           unit: '',     conf: 0.91 },
  { id: 'height',     label: 'Building height',    value: '39.2',           unit: 'm',    conf: 0.95 },
  { id: 'storeys',    label: 'Storeys',            value: 'G + 12',         unit: '',     conf: 0.99 },
  { id: 'zone',       label: 'Seismic zone',       value: 'IV',             unit: '',     conf: 0.97 },
  { id: 'occupancy',  label: 'Occupancy',          value: 'Residential',    unit: '',     conf: 0.96 },
  { id: 'concrete',   label: 'Concrete grade',     value: 'M30',            unit: '',     conf: 0.99 },
  { id: 'steel',      label: 'Reinforcement',      value: 'Fe500',          unit: '',     conf: 0.99 },
  { id: 'exposure',   label: 'Exposure',           value: 'Severe',         unit: '',     conf: 0.88 },
  { id: 'foundation', label: 'Foundation',         value: 'Raft',           unit: '',     conf: 0.93 },
  { id: 'sbc',        label: 'Safe bearing cap.',  value: '250',            unit: 'kN/m²',conf: 0.84 },
  { id: 'wind',       label: 'Basic wind speed',   value: '44',             unit: 'm/s',  conf: 0.90 },
];

// Severity labels (secondary, paired with verdict)
// 25 findings. expected / found are short, tabular strings.
const CHECKS = [
  // ---- Identity / QA ----
  { id: 'D01', cat: 'Identity / QA', verdict: 'PASS', sev: 'info',
    title: 'Project identification block present',
    summary: 'Title, location, client and document revision are all stated on the cover sheet.',
    expected: 'All 5 fields', found: '5 / 5 fields',
    code: 'NBC 2016', clause: 'Part 2 · 3.1', page: 'p. 7',
    clauseText: 'Every structural document shall carry an identification block stating the project title, location, the responsible engineer, the issue/revision status and the date of issue.' },
  { id: 'D02', cat: 'Identity / QA', verdict: 'REVIEW', sev: 'minor',
    title: 'Issue & revision sign-off',
    summary: 'Revision is marked R2 but the design-checker signature field is blank — verify the document is approved for issue.',
    expected: 'Signed + dated', found: 'R2 · checker unsigned',
    code: 'NBC 2016', clause: 'Part 2 · 3.4', page: 'p. 8',
    clauseText: 'No structural document shall be issued for construction unless it bears the signature of the designer and an independent design checker, together with the date of approval.' },

  // ---- Currency ----
  { id: 'D03', cat: 'Currency', verdict: 'PASS', sev: 'info',
    title: 'IS 456 edition is current',
    summary: 'Concrete design references IS 456:2000 (incl. Amendment 4, 2019) — the current edition.',
    expected: 'IS 456:2000', found: 'IS 456:2000 (A4)',
    code: 'IS 456', clause: '2000', page: 'cover',
    clauseText: 'IS 456:2000 “Plain and Reinforced Concrete — Code of Practice” (Fourth Revision), incorporating Amendments 1–4, remains the governing code for RC design in India.' },
  { id: 'D04', cat: 'Currency', verdict: 'FLAW', sev: 'major',
    title: 'Superseded seismic code referenced',
    summary: 'DBR cites IS 1893:2002 for seismic loading. That edition is withdrawn; design must use IS 1893 (Part 1):2016.',
    expected: 'IS 1893-1:2016', found: 'IS 1893:2002',
    code: 'IS 1893-1', clause: '2016 · Foreword', page: 'p. ii',
    clauseText: 'This 2016 revision supersedes the 2002 edition of IS 1893 (Part 1). Structures designed after its publication shall comply with the revised zone factors, spectra and load combinations.' },

  // ---- Materials ----
  { id: 'D05', cat: 'Materials', verdict: 'PASS', sev: 'info',
    title: 'Minimum concrete grade for durability',
    summary: 'Severe exposure requires M30 minimum; DBR specifies M30 for all structural members.',
    expected: '≥ M30', found: 'M30',
    code: 'IS 456', clause: 'Table 5', page: 'p. 20',
    clauseText: 'For severe exposure, the minimum grade of reinforced concrete is M30 with a minimum cement content of 320 kg/m³ and a maximum free water-cement ratio of 0.45.' },
  { id: 'D06', cat: 'Materials', verdict: 'PASS', sev: 'info',
    title: 'Reinforcement grade declared',
    summary: 'Fe500 conforming to IS 1786 is specified for all main and distribution steel.',
    expected: 'Fe415 / Fe500', found: 'Fe500',
    code: 'IS 1786', clause: '2008 · cl 5', page: 'p. 3',
    clauseText: 'High-strength deformed steel bars of grades Fe415, Fe500 and Fe550 shall conform to the chemical, mechanical and bond-property requirements of this standard.' },
  { id: 'D07', cat: 'Materials', verdict: 'REVIEW', sev: 'minor',
    title: 'Maximum cement content',
    summary: 'DBR fixes cement at 400 kg/m³. Cap of 450 kg/m³ is met, but verify against shrinkage control for the raft pour.',
    expected: '≤ 450 kg/m³', found: '400 kg/m³',
    code: 'IS 456', clause: 'cl 8.2.4.2', page: 'p. 19',
    clauseText: 'The total quantity of cementitious material in the concrete shall not normally exceed 450 kg/m³ to limit the risk of cracking due to the heat of hydration and drying shrinkage.' },

  // ---- Cover / Durability / Fire ----
  { id: 'D08', cat: 'Cover / Durability / Fire', verdict: 'FLAW', sev: 'major',
    title: 'Nominal cover for severe exposure',
    summary: 'Schedule shows 30 mm clear cover to columns. Severe exposure mandates 45 mm — increase cover or revise exposure basis.',
    expected: '≥ 45 mm', found: '30 mm',
    code: 'IS 456', clause: 'Table 16', page: 'p. 47',
    clauseText: 'For severe exposure conditions the nominal cover to all reinforcement, including links, shall be not less than 45 mm. This may be reduced by 5 mm where concrete grade is M35 or above.' },
  { id: 'D09', cat: 'Cover / Durability / Fire', verdict: 'PASS', sev: 'info',
    title: 'Exposure condition declared',
    summary: 'Coastal Mumbai site correctly classified as “Severe” exposure, consistent with the durability basis.',
    expected: 'Stated', found: 'Severe',
    code: 'IS 456', clause: 'Table 3', page: 'p. 18',
    clauseText: 'Concrete surfaces exposed to sea-water spray, corrosive fumes or severe freezing whilst wet shall be classified under the “severe” environmental exposure condition.' },
  { id: 'D10', cat: 'Cover / Durability / Fire', verdict: 'MISSING', sev: 'major',
    title: 'Fire resistance — cover to slab',
    summary: 'Required fire rating (2 h) is not stated, and the cover-for-fire check is absent from the DBR.',
    expected: '2 h rating + cover', found: 'Not stated',
    code: 'IS 456', clause: 'Table 16A', page: 'p. 48',
    clauseText: 'To achieve a 2-hour fire resistance for a simply-supported slab, a minimum nominal cover of 35 mm to the main reinforcement and a minimum thickness as tabulated shall be provided.' },

  // ---- Seismic ----
  { id: 'D11', cat: 'Seismic', verdict: 'PASS', sev: 'info',
    title: 'Seismic zone factor Z',
    summary: 'Site in Zone IV; Z = 0.24 used in the base-shear computation — matches the code map.',
    expected: 'Z = 0.24', found: 'Z = 0.24',
    code: 'IS 1893-1', clause: 'Table 3', page: 'p. 11',
    clauseText: 'The zone factor Z for the Maximum Considered Earthquake (MCE) is 0.10, 0.16, 0.24 and 0.36 for Seismic Zones II, III, IV and V respectively.' },
  { id: 'D12', cat: 'Seismic', verdict: 'PASS', sev: 'info',
    title: 'Importance factor I',
    summary: 'Residential occupancy → I = 1.0 applied. Correct for a non-essential building.',
    expected: 'I = 1.0', found: 'I = 1.0',
    code: 'IS 1893-1', clause: 'Table 8', page: 'p. 16',
    clauseText: 'An importance factor I of 1.2 applies to residential and commercial buildings with occupancy above 200 persons; otherwise I = 1.0 unless a higher value is warranted.' },
  { id: 'D13', cat: 'Seismic', verdict: 'FLAW', sev: 'critical',
    title: 'Response reduction factor R vs detailing',
    summary: 'R = 5.0 (Special MRF) used, but the DBR does not commit to IS 13920 ductile detailing — R = 5 is not permissible without it.',
    expected: 'R=5 ⇒ SMRF detail', found: 'R=5, detail TBC',
    code: 'IS 1893-1', clause: 'Table 9', page: 'p. 17',
    clauseText: 'A response reduction factor R of 5.0 may be used only for a special moment-resisting frame detailed to comply with IS 13920. For an ordinary moment-resisting frame, R shall not exceed 3.0.' },
  { id: 'D14', cat: 'Seismic', verdict: 'REVIEW', sev: 'major',
    title: 'Ductile detailing (IS 13920) scope',
    summary: 'DBR mentions IS 13920 but does not confirm confinement, hook angles or strong-column/weak-beam at all joints.',
    expected: 'Full clause 6–8', found: 'Referenced only',
    code: 'IS 13920', clause: 'cl 6–8', page: 'p. 9',
    clauseText: 'Members of lateral-force-resisting RC frames in Zones III–V shall satisfy the ductile-detailing provisions of clauses 6 to 8, including special confining reinforcement and 135° hooks.' },

  // ---- Wind ----
  { id: 'D15', cat: 'Wind', verdict: 'PASS', sev: 'info',
    title: 'Basic wind speed Vb',
    summary: 'Mumbai basic wind speed of 44 m/s adopted — consistent with the wind-zone map.',
    expected: 'Vb = 44 m/s', found: '44 m/s',
    code: 'IS 875-3', clause: 'Annex A · Fig 1', page: 'p. 51',
    clauseText: 'The basic wind speed Vb is based on peak-gust velocity averaged over 3 s with a 50-year return period; for the Mumbai region the mapped value is 44 m/s.' },
  { id: 'D16', cat: 'Wind', verdict: 'MISSING', sev: 'minor',
    title: 'Terrain category & risk coefficients',
    summary: 'Terrain category, k1/k2/k3 factors and the design wind pressure are not tabulated in the DBR.',
    expected: 'k1·k2·k3 stated', found: 'Not stated',
    code: 'IS 875-3', clause: 'cl 6.3', page: 'p. 9',
    clauseText: 'The design wind speed Vz is obtained as Vb·k1·k2·k3 where k1 is the risk coefficient, k2 the terrain-height-structure factor and k3 the topography factor.' },
  { id: 'D17', cat: 'Wind', verdict: 'REVIEW', sev: 'major',
    title: 'Dynamic (gust) wind analysis',
    summary: 'Height 39 m with low fundamental frequency suggests a gust-factor analysis is required; DBR shows static only.',
    expected: 'Dynamic if f<1 Hz', found: 'Static only',
    code: 'IS 875-3', clause: 'cl 10', page: 'p. 33',
    clauseText: 'Buildings taller than 50 m, or with a height-to-least-width ratio above 5, or a natural frequency below 1.0 Hz, shall be examined for dynamic along-wind response using the gust-factor method.' },

  // ---- Loads / Temperature ----
  { id: 'D18', cat: 'Loads / Temperature', verdict: 'PASS', sev: 'info',
    title: 'Imposed (live) load per occupancy',
    summary: 'Residential floors take 2.0 kN/m² and balconies 3.0 kN/m² — correct for the occupancy.',
    expected: '2.0 kN/m²', found: '2.0 kN/m²',
    code: 'IS 875-2', clause: 'Table 1', page: 'p. 5',
    clauseText: 'For residential buildings the minimum imposed floor load is 2.0 kN/m² on all rooms and 3.0 kN/m² on balconies and corridors subject to crowd loading.' },
  { id: 'D19', cat: 'Loads / Temperature', verdict: 'PASS', sev: 'info',
    title: 'Load combinations',
    summary: 'Limit-state combinations including 1.5(DL+LL) and seismic 1.2(DL+LL±EL) are listed correctly.',
    expected: 'All LS combos', found: '7 / 7 combos',
    code: 'IS 456', clause: 'Table 18', page: 'p. 68',
    clauseText: 'The partial safety factors for load combinations under the limit-state method shall be applied as tabulated, including 1.5 for dead and imposed loads and 1.2 with earthquake effects.' },
  { id: 'D20', cat: 'Loads / Temperature', verdict: 'MISSING', sev: 'major',
    title: 'Expansion / temperature joints',
    summary: 'Plan length 48 m exceeds the 45 m guideline, but no expansion joint or thermal analysis is provided.',
    expected: 'Joint if > 45 m', found: 'Not addressed',
    code: 'IS 456', clause: 'cl 27', page: 'p. 65',
    clauseText: 'Structures exceeding 45 m in length are generally designed with one or more expansion joints, unless the effects of temperature, creep and shrinkage are explicitly analysed.' },

  // ---- Foundation ----
  { id: 'D21', cat: 'Foundation', verdict: 'PASS', sev: 'info',
    title: 'Safe bearing capacity stated',
    summary: 'Net SBC of 250 kN/m² from the geotechnical report is quoted and used in raft sizing.',
    expected: 'SBC stated', found: '250 kN/m²',
    code: 'IS 1904', clause: 'cl 5', page: 'p. 4',
    clauseText: 'The allowable bearing pressure used in design shall be the lesser of the value governed by shear failure and that governed by permissible total and differential settlement.' },
  { id: 'D22', cat: 'Foundation', verdict: 'REVIEW', sev: 'minor',
    title: 'Foundation type vs soil profile',
    summary: 'Raft chosen for medium-stiff clay. Reasonable, but confirm raft rigidity and the bearing assumption with the soil report.',
    expected: 'Justified', found: 'Raft, basis brief',
    code: 'IS 1904', clause: 'cl 6', page: 'p. 6',
    clauseText: 'The type of foundation shall be selected with regard to the nature of the loading, the soil strata, the depth of the water table and the permissible settlement of the structure.' },
  { id: 'D23', cat: 'Foundation', verdict: 'MISSING', sev: 'major',
    title: 'Settlement check',
    summary: 'Total and differential settlement limits for the raft are not reported.',
    expected: 'Settlement ≤ limits', found: 'Not reported',
    code: 'IS 1904', clause: 'Table 1', page: 'p. 9',
    clauseText: 'For raft foundations on clay the permissible maximum total settlement is 75 mm and the permissible differential settlement is limited to 1 in 500 of the span.' },

  // ---- Location ----
  { id: 'D24', cat: 'Location', verdict: 'NA', sev: 'info',
    title: 'Seismic micro-zonation overlay',
    summary: 'Project city has no published micro-zonation map, so the site-specific overlay check does not apply.',
    expected: 'If map exists', found: 'No map published',
    code: 'IS 1893-1', clause: 'cl 3.16', page: 'p. 8',
    clauseText: 'Where a seismic micro-zonation study is available for the region, the site-specific zone factor from that study shall take precedence over the macro-zone value.' },
  { id: 'D25', cat: 'Location', verdict: 'NA', sev: 'info',
    title: 'Tall-building provisions (IS 16700)',
    summary: 'Building height of 39 m is below the 50 m threshold, so the additional tall-building criteria do not apply.',
    expected: 'If H > 50 m', found: 'H = 39 m',
    code: 'IS 16700', clause: 'cl 1.1', page: 'p. 1',
    clauseText: 'This standard provides additional criteria for the structural design of reinforced-concrete buildings taller than 50 m and up to 250 m in height.' },
];

// codes covered, for the landing page
const CODES = [
  { code: 'IS 456',   year: '2000', title: 'Plain & Reinforced Concrete' },
  { code: 'IS 1893',  year: '2016', title: 'Earthquake Resistant Design' },
  { code: 'IS 13920', year: '2016', title: 'Ductile Detailing of RC' },
  { code: 'IS 875-3', year: '2015', title: 'Wind Loads' },
  { code: 'IS 875-5', year: '1987', title: 'Special Loads & Combinations' },
  { code: 'IS 16700', year: '2017', title: 'Tall Concrete Buildings' },
  { code: 'IS 269',   year: '2015', title: 'Ordinary Portland Cement' },
  { code: 'NBC 2016', year: '2016', title: 'National Building Code' },
];

Object.assign(window, { DBR_META, EXTRACTED, CHECKS, CODES });
