"""add district_locations table

Revision ID: 27e4b2549dc5
Revises: 6ac7aa0f3412
Create Date: 2026-06-10 00:51:04.711214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e4b2549dc5'
down_revision: Union[str, None] = '6ac7aa0f3412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_locations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=160), nullable=False),
    sa.Column('zone_conservative', sa.String(length=4), nullable=True),
    sa.Column('zone_majority', sa.String(length=4), nullable=True),
    sa.Column('zone_span', sa.String(length=12), nullable=True),
    sa.Column('is_straddler', sa.Boolean(), nullable=False),
    sa.Column('basic_wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_source', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_district_locations_district'), 'district_locations', ['district'], unique=False)
    op.create_index(op.f('ix_district_locations_state'), 'district_locations', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_district_locations_state'), table_name='district_locations')
    op.drop_index(op.f('ix_district_locations_district'), table_name='district_locations')
    op.drop_table('district_locations')
    # ### end Alembic commands ###
