"use client";

import { useParams } from "next/navigation";
import React from "react";
import { getReport } from "@/lib/api";
import type { AnalyzeResponse, Finding, Verdict } from "@/lib/types";
import { fmtValue } from "@/lib/format";
import { CATEGORY_ORDER, CHECK_CATEGORY, VERDICTS } from "@/lib/design";
import { CHECK_META } from "@/lib/checkMeta";

const ALL_VERDICTS: Verdict[] = ["FLAW", "MISSING", "REVIEW", "PASS", "NOT_APPLICABLE"];

// Document-style print report (D1–D25), modelled on the vetting-report DOCX.
// Plain serif document look; opens the print dialog automatically.
export default function PrintReportPage() {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = React.useState<AnalyzeResponse | null>(null);
  const [err, setErr] = React.useState<string | null>(null);

  React.useEffect(() => {
    const cached = typeof window !== "undefined" ? sessionStorage.getItem(`dbr-report-${id}`) : null;
    if (cached) {
      try { setData(JSON.parse(cached)); return; } catch { /* fall through */ }
    }
    getReport(id).then(setData).catch((e) => setErr(e instanceof Error ? e.message : "Could not load report."));
  }, [id]);

  // Auto-open print dialog once the document has rendered.
  React.useEffect(() => {
    if (data) {
      const t = setTimeout(() => window.print(), 600);
      return () => clearTimeout(t);
    }
  }, [data]);

  if (err) return <div style={{ padding: 40, fontFamily: "Georgia, serif" }}>Couldn&rsquo;t load report: {err}</div>;
  if (!data) return <div style={{ padding: 40, fontFamily: "Georgia, serif" }}>Preparing report…</div>;

  const tb = data.extracted.title_block || {};
  const p = data.extracted.profile;
  const counts = data.summary;
  const total = data.findings.length;
  const project = tb.project || data.extracted.title_block?.project || "Untitled project";

  // sort findings into reading order: by category, FLAW/MISSING first within each
  const ordered: { cat: string; items: Finding[] }[] = CATEGORY_ORDER
    .map((cat) => ({
      cat,
      items: data.findings
        .filter((f) => CHECK_CATEGORY[f.check_id] === cat)
        .sort((a, b) => VERDICTS[b.verdict].weight - VERDICTS[a.verdict].weight),
    }))
    .filter((g) => g.items.length > 0);

  let idx = 0;

  return (
    <div className="doc">
      <PrintStyles />
      <ToolbarNoPrint />

      {/* ---- Title block ---- */}
      <header className="doc-head">
        <div className="doc-kicker">DBR COMPLIANCE — METHODOLOGY &amp; FINDINGS</div>
        <h1 className="doc-title">{project}</h1>
        <table className="meta-grid">
          <tbody>
            <MetaRow k="Document" v={`${tb.document_no || "—"}${tb.revision ? ` (Rev ${tb.revision})` : ""}${tb.date ? `, ${tb.date}` : ""}`} />
            <MetaRow k="Building" v={[p.material, p.structural_system, p.height_m ? `${p.height_m} m` : null, p.num_storeys ? `${p.num_storeys} storeys` : null].filter(Boolean).join(" · ") || "—"} />
            <MetaRow k="Site basis" v={[p.district, p.seismic_zone ? `Seismic Zone ${p.seismic_zone}` : null, p.basic_wind_speed ? `Vb ${p.basic_wind_speed} m/s` : null, p.soil_type ? `Soil ${p.soil_type}` : null].filter(Boolean).join(" · ") || "—"} />
            <MetaRow k="Occupancy" v={[p.occupancy ? `NBC Group ${p.occupancy}` : null, p.foundation_type].filter(Boolean).join(" · ") || "—"} />
            <MetaRow k="Software" v={data.extracted.software_used || "—"} />
            <MetaRow k="Generated by" v={`DBR Check (CivilSpace)${data.extraction_model ? ` · extraction: ${data.extraction_model}` : ""}`} />
          </tbody>
        </table>

        <div className="legend">
          <b>Legend — Status:</b> PASS (compliant) · FLAW (does not meet code / DBR) · REVIEW (needs engineer judgement) · MISSING (not stated) · N/A (out of scope).
        </div>

        {/* summary line */}
        <div className="summary-strip">
          {ALL_VERDICTS.map((k) => (
            <span key={k} className="summary-chip">
              <span className="dot" style={{ background: VERDICTS[k].solid }} />
              {VERDICTS[k].label.toUpperCase()} <b>{counts[k] ?? 0}</b>
            </span>
          ))}
          <span className="summary-chip">TOTAL <b>{total}</b></span>
        </div>
      </header>

      {/* ---- Findings, grouped ---- */}
      <h2 className="part">PART 1 — Design Basis Report (DBR) Review · D1–D25</h2>
      {ordered.map((g) => (
        <section key={g.cat} className="cat">
          <h3 className="cat-title">{g.cat}</h3>
          {g.items.map((f) => {
            idx += 1;
            return <CheckBlock key={f.check_id} f={f} n={idx} />;
          })}
        </section>
      ))}

      <footer className="doc-foot">
        Generated by DBR Check (CivilSpace) · code checks against IS 456, IS 1893, IS 13920, IS 875-3/5, IS 16700, IS 269, NBC 2016.
        Verdicts are produced by a deterministic engine; clause text is from the digitised IS-code corpus. AI explanations are advisory.
      </footer>
    </div>
  );
}

function MetaRow({ k, v }: { k: string; v: string }) {
  return (
    <tr><td className="meta-k">{k}</td><td className="meta-v">{v}</td></tr>
  );
}

function CheckBlock({ f, n }: { f: Finding; n: number }) {
  const v = VERDICTS[f.verdict];
  const meta = CHECK_META[f.check_id];
  const clauseText = (f.citations || []).find((c) => !c.missing && c.statement);
  return (
    <div className="check">
      <div className="check-head">
        <span className="check-id">{f.check_id}</span>
        <span className="check-title">{f.title}</span>
        <span className="check-status" style={{ color: v.fg, borderColor: v.line, background: v.bg }}>{v.label.toUpperCase()}</span>
      </div>

      <table className="check-grid">
        <tbody>
          {meta && <Row k="Governing code & clause" v={meta.governing} />}
          {meta && <Row k="Method" v={meta.method} />}
          <Row k="Finding" v={f.summary} />
          {f.expected != null && <Row k="Expected" v={fmtValue(f.expected)} mono />}
          {f.found != null && <Row k="Found" v={fmtValue(f.found)} mono flag={f.verdict === "FLAW" || f.verdict === "MISSING"} />}
          {f.citation && <Row k="Citation" v={f.citation} />}
          {f.ai_explanation && <Row k="Explanation" v={f.ai_explanation} />}
          {f.notes && f.notes.length > 0 && <Row k="Notes" v={f.notes.join("  •  ")} />}
        </tbody>
      </table>

      {clauseText && (
        <div className="clause">
          <div className="clause-h">{clauseText.code} {clauseText.clause ? `· ${clauseText.clause}` : ""}{clauseText.title ? ` — ${clauseText.title}` : ""}{clauseText.page ? ` (p.${clauseText.page})` : ""}</div>
          <div className="clause-b">{clauseText.statement}</div>
        </div>
      )}
    </div>
  );
}

function Row({ k, v, mono, flag }: { k: string; v: string; mono?: boolean; flag?: boolean }) {
  return (
    <tr>
      <td className="rk">{k}</td>
      <td className={`rv${mono ? " mono" : ""}${flag ? " flag" : ""}`}>{v}</td>
    </tr>
  );
}

function ToolbarNoPrint() {
  return (
    <div className="no-print toolbar">
      <button onClick={() => window.print()}>Print / Save as PDF</button>
      <button onClick={() => window.close()} className="ghost">Close</button>
      <span className="hint">This document opens the print dialog automatically. Choose “Save as PDF”.</span>
    </div>
  );
}

function PrintStyles() {
  return (
    <style>{`
      .doc { max-width: 820px; margin: 0 auto; padding: 40px 48px 80px; color: #1A1A1A;
        font-family: Georgia, "Times New Roman", serif; font-size: 12.5px; line-height: 1.55; background: #fff; }
      .doc-kicker { font-family: ui-monospace, monospace; font-size: 10px; letter-spacing: 0.14em; color: #6B6860; }
      .doc-title { font-size: 26px; margin: 6px 0 16px; font-weight: 700; letter-spacing: -0.01em; }
      .meta-grid { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
      .meta-k { width: 130px; vertical-align: top; padding: 3px 10px 3px 0; color: #6B6860; font-size: 11.5px; }
      .meta-v { padding: 3px 0; font-size: 12.5px; }
      .legend { font-size: 11px; color: #444; border-left: 3px solid #E08A00; padding: 6px 12px; background: #faf7f2; margin-bottom: 14px; }
      .summary-strip { display: flex; flex-wrap: wrap; gap: 14px; padding: 10px 0; border-top: 2px solid #1A1A1A; border-bottom: 1px solid #ddd; font-family: ui-monospace, monospace; font-size: 11px; }
      .summary-chip { display: inline-flex; align-items: center; gap: 6px; }
      .summary-chip .dot { width: 9px; height: 9px; border-radius: 999px; display: inline-block; }
      .part { font-size: 15px; margin: 26px 0 4px; padding-bottom: 6px; border-bottom: 1px solid #1A1A1A; }
      .cat { margin-top: 14px; }
      .cat-title { font-size: 14px; color: #0E7490; margin: 14px 0 8px; }
      .check { border: 1px solid #ddd; border-left: 3px solid #999; border-radius: 6px; padding: 10px 14px; margin-bottom: 10px; break-inside: avoid; page-break-inside: avoid; }
      .check-head { display: flex; align-items: baseline; gap: 8px; margin-bottom: 6px; }
      .check-id { font-family: ui-monospace, monospace; font-weight: 700; font-size: 12px; }
      .check-title { font-weight: 700; font-size: 13.5px; flex: 1; }
      .check-status { font-family: ui-monospace, monospace; font-size: 9.5px; font-weight: 700; letter-spacing: 0.08em; border: 1px solid; border-radius: 4px; padding: 1px 6px; }
      .check-grid { width: 100%; border-collapse: collapse; }
      .rk { width: 150px; vertical-align: top; color: #6B6860; font-size: 10.5px; padding: 2px 10px 2px 0; text-transform: uppercase; letter-spacing: 0.03em; font-family: ui-monospace, monospace; }
      .rv { padding: 2px 0; font-size: 12px; vertical-align: top; }
      .rv.mono { font-family: ui-monospace, monospace; font-size: 11.5px; }
      .rv.flag { color: #BE123C; font-weight: 600; }
      .clause { margin-top: 8px; background: #FAF6EC; border: 1px solid #e7e0cf; border-radius: 5px; padding: 8px 12px; }
      .clause-h { font-family: ui-monospace, monospace; font-size: 10px; color: #8a7a5a; margin-bottom: 4px; }
      .clause-b { font-size: 11.5px; color: #2A2620; line-height: 1.65; }
      .doc-foot { margin-top: 28px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 10px; color: #6B6860; }
      .toolbar { position: sticky; top: 0; display: flex; align-items: center; gap: 12px; padding: 12px 0; margin-bottom: 18px; border-bottom: 1px solid #eee; background: #fff; }
      .toolbar button { font-family: Inter, system-ui, sans-serif; font-size: 13px; font-weight: 600; padding: 9px 16px; border-radius: 8px; border: none; background: #0A1628; color: #fff; cursor: pointer; }
      .toolbar button.ghost { background: #fff; color: #0A1628; border: 1px solid #ddd; }
      .toolbar .hint { font-family: Inter, system-ui, sans-serif; font-size: 12px; color: #6B6860; }
      @media print {
        @page { margin: 14mm 14mm; size: A4; }
        .no-print { display: none !important; }
        .doc { max-width: none; padding: 0; }
        .check { box-shadow: none; }
      }
    `}</style>
  );
}
